#!/bin/sh

set -e

case "${1}" in
  prereqs)
    exit 0
    ;;
esac

get_variables () {
  ROOT_PART_DEV="$(resolve_device "$ROOT")"
  ROOT_PART_NAME="$(lsblk -no kname "$ROOT_PART_DEV")"

  ROOT_DEV_NAME="$(lsblk -no pkname "$ROOT_PART_DEV")"
  ROOT_DEV="/dev/$ROOT_DEV_NAME"

  ROOT_PART_NUM=$(cat "/sys/block/$ROOT_DEV_NAME/$ROOT_PART_NAME/partition")

  ROOT_DEV_SIZE=$(cat "/sys/block/$ROOT_DEV_NAME/size")
  TARGET_END="$((ROOT_DEV_SIZE - 1))"
}

do_resize () {
  if ! parted -m "$ROOT_DEV" u s resizepart "$ROOT_PART_NUM" "$TARGET_END"; then
    FAIL_REASON="Partition table resize of the root partition ($ROOT_PART_DEV) failed\n$FAIL_REASON"
    return 1
  fi

  resize2fs -f -p "$ROOT_PART_DEV"
  RET="$?"
  if [ "$RET" -ne 0 ]; then
    FAIL_REASON="Root partition resize failed\n$FAIL_REASON"
  fi

  return "$RET"
}

if ! grep -q firstboot /proc/cmdline; then
  exit 0
fi

. /scripts/functions
. /scripts/local

log_begin_msg "Resizing root filesystem...\n\nDepending on storage size and speed, this may take a while."

get_variables
do_resize

log_end_msg

exit 0
