#!/bin/sh

set -e

PREREQ=""

prereqs () {
  echo "${PREREQ}"
}

case "${1}" in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

if ! ischroot; then
  exit 0
fi

copy_exec /usr/bin/lsblk /bin
copy_exec /usr/sbin/parted /bin
copy_exec /usr/sbin/resize2fs /bin

exit 0
