#!/bin/sh

set -e

PREREQ=""

prereqs () {
  echo "${PREREQ}"
}

case "${1}" in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules i2c-brcmstb

exit 0
