#!/bin/sh

set -e

usage () {
  if [ "$#" -eq "0" ]; then
    usage set_hostname enable_ssh set_wlan set_keymap set_timezone
    return 0
  fi
  echo "Usage: "
  for arg in "$@"; do
    case "$arg" in
      set_hostname)
        echo "  $0 set_hostname HOSTNAME"
        ;;
      enable_ssh)
        echo "  $0 enable_ssh [-k|--key-only] [KEY_LINE1 [KEY_LINE2]...]"
        ;;
      set_wlan)
        echo "  $0 set_wlan [-h|--hidden] SSID [PASS [COUNTRY]]"
        ;;
      set_keymap)
        echo "  $0 set_keymap KEYMAP"
        ;;
      set_timezone)
        echo "  $0 set_timezone TIMEZONE"
        ;;
    esac
  done
  }

set_hostname () (
  if [ "$#" -ne 1 ]; then
    usage set_hostname
    exit 1
  fi
  HOSTNAME="$1"
  raspi-config nonint do_hostname "$HOSTNAME"
  echo "$HOSTNAME" > /etc/hostname
)

enable_ssh () (
  FIRSTUSER=$(getent passwd 1000 | cut -d: -f1)
  FIRSTUSERHOME=$(getent passwd 1000 | cut -d: -f6)
  SSH_DIR="$FIRSTUSERHOME/.ssh"
  AUTHORISED_KEYS_FILE="$SSH_DIR/authorized_keys"
  SED_STR='s/^[#\s]*PasswordAuthentication\s\+\S\+$/PasswordAuthentication no/'
  for arg in "$@"; do
    if [ "$arg" = "-k" ] || [ "$arg" = "--key-only" ]; then
      sed -i "$SED_STR" /etc/ssh/sshd_config
    else
      if ! [ -d "$SSH_DIR" ]; then
        install -o "$FIRSTUSER" -g "$FIRSTUSER" -m 700 -d "$SSH_DIR"
      fi
      echo "$arg" >> "$AUTHORISED_KEYS_FILE"
    fi
  done
  if [ -f "$AUTHORISED_KEYS_FILE" ]; then
    chmod 600 "$AUTHORISED_KEYS_FILE"
    chown "$FIRSTUSER:$FIRSTUSER" "$AUTHORISED_KEYS_FILE"
  fi
  systemctl enable ssh
)

set_wlan () (
  HIDDEN=0
  PLAIN=0
  SCRIPT='/var/lib/raspberrypi-sys-mods/set-wlan'
  for arg in "$@"; do
    if [ "$arg" = "-h" ] || [ "$arg" = "--hidden" ]; then
      HIDDEN=1
    elif [ "$arg" = "-p" ] || [ "$arg" = "--plain" ]; then
      PLAIN=1
    elif [ -z "${SSID+set}" ]; then
      SSID="$arg"
    elif [ -z "${PASS+set}" ]; then
      PASS="$arg"
    elif [ -z "${COUNTRY+set}" ]; then
      COUNTRY="$arg"
    else
      usage set_wlan
      exit 1
    fi
  done
  if [ -z "${SSID+set}" ]; then
    usage set_wlan
    exit 1
  fi
  if [ -e /boot/wpa_supplicant.conf ]; then
    echo "Ignoring network configuration: /boot/wpa_supplicant.conf exists"
    exit 0
  fi
  mkdir -p "$(dirname "$SCRIPT")"
  # shellcheck disable=SC2094
  cat <<- EOF > "$SCRIPT"
	#!/bin/sh
	set -e
	$([ -n "$COUNTRY" ] && echo "raspi-config nonint do_wifi_country \"$COUNTRY\"")
	COUNTER=0
	while [ "\$COUNTER" -lt 10 ]; do
	  COUNTER=\$((COUNTER + 1))
	  if raspi-config nonint do_wifi_ssid_passphrase  "$SSID" "$PASS" "$HIDDEN" "$PLAIN"; then
	    break
	  fi
	  sleep 5
	done
	systemctl stop set-wlan.timer
	systemctl disable set-wlan.timer
	rm -f "\$0"
	rm -f /etc/systemd/system/set-wlan.timer
	rm -f /etc/systemd/system/set-wlan.service
	rmdir --ignore-fail-on-non-empty "$(dirname "$SCRIPT")"
	EOF
  chmod 700 "$SCRIPT"

  cat <<- EOF > /etc/systemd/system/set-wlan.timer
		[Unit]
		Description=Configure WLAN for rpi-imager
		[Timer]
		OnBootSec=1
		OnUnitActiveSec=10
		[Install]
		WantedBy=timers.target
	EOF

  cat <<- EOF > /etc/systemd/system/set-wlan.service
		[Unit]
		Description=Configure WLAN for rpi-imager
		After=NetworkManager.service
		ConditionPathIsDirectory=/run/wpa_supplicant
		[Service]
		Type=oneshot
		ExecStart=$SCRIPT
	EOF
  ln -f -s /etc/systemd/system/set-wlan.timer \
  /etc/systemd/system/timers.target.wants/set-wlan.timer
)

set_keymap () (
  if [ "$#" -ne 1 ]; then
    usage set_keymap
    exit 1
  fi
  raspi-config nonint do_configure_keyboard "$1"
)

set_timezone () (
  if [ "$#" -ne 1 ]; then
    usage set_timezone
    exit 1
  fi
  raspi-config nonint do_change_timezone "$1"
)

if [ "$#" -eq 0 ]; then
  echo "No command specified"
  usage
  exit 1
fi

command="$1"; shift
case "$command" in
  set_hostname|enable_ssh|set_wlan|set_keymap|set_timezone)
    "$command" "$@"
    ;;
  *)
    echo "Unsupported command: $command"
    usage
    exit 1
    ;;
esac
