#!/bin/sh

state=${1:-1}

if [ ! -x "/usr/sbin/rfkill" ]; then
	echo "rfkill not installed"
	exit 1
fi
mkdir -p "/var/lib/systemd/rfkill"

address="$(/bin/grep -m 1 @7e300000 /proc/iomem | /usr/bin/cut -f1 -d-)"
if [ -z "$address" ]; then
	echo "Could not determine WiFi iomem address"
	exit 1
fi
persist_file="/var/lib/systemd/rfkill/platform-$address.mmc:wlan"

/bin/echo ${state} > "$persist_file"
