#!/bin/sh

if ! /bin/grep -q '^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[dD][0-9a-fA-F]$' /proc/cpuinfo ; then
	exit 0
fi

if /bin/grep -q "^country=[A-Z][A-Z]" /etc/wpa_supplicant/wpa_supplicant.conf; then
	exit 0
fi

/usr/lib/raspberrypi-sys-mods/rfkill-wifi 1
/usr/bin/touch /run/wifi-country-unset
/bin/echo "Wi-Fi is disabled because the country is not set"
